### PR TITLE
Enable Psalm

### LINKED ISSUE #16: Psalm integration
### Feature Request

|    Q        |   A
|------------ | ------
| QA    | yes

#### Summary

As decided during the [Technical-Steering-Committee Meeting on August 3rd, 2020](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-static-analysis-tooling), Laminas wants to implement [vimeo/psalm](https://github.com/vimeo/psalm) in all packages.

Implementing psalm is quite easy.

#### Required
- [ ] Create a `psalm.xml` in the project root
- [ ] Copy and paste the contents from this [psalm.xml.dist](https://github.com/mezzio/repo-template/blob/6124090610ef1c6d6b0c80a063cafacc3ec68f38/psalm.xml.dist)
- [ ] Run `$ composer require --dev vimeo/psalm`
- [ ] Run `$ vendor/bin/psalm --set-baseline=psalm-baseline.xml`
- [ ] Add a composer script `static-analysis` with the command `psalm --shepherd --stats`
- [ ] Add a new line to `script:` in `.travis.yml`: `- if [[ $TEST_COVERAGE == 'true' ]]; then composer static-analysis ; fi`
- [ ] Remove phpstan from the project (`phpstan.neon.dist`, `.travis.yml` entry, `composer.json` `require-dev` and `scripts`)

##### Optional
- [ ] Fix as many psalm errors as possible.

### LINKED ISSUE #17: PHP 8.0 support
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [ ] Modify `composer.json` to provide support for PHP 8.0 by adding the constraint `~8.0.0`
- [ ] Modify `composer.json` to drop support for PHP less than 7.3
- [ ] Modify `composer.json` to implement phpunit 9.3 which supports PHP 7.3+
- [ ] Modify `.travis.yml` to ignore platform requirements when installing composer dependencies (simply add `--ignore-platform-reqs` to `COMPOSER_ARGS` env variable)
- [ ] Modify `.travis.yml` to add PHP 8.0 to the matrix (*NOTE*: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [ ] Modify source code in case there are incompatibilities with PHP 8.0

### PR DESCRIPTION
**Pull request by datasage**
Fixed a couple of identified issues. More will be able to be fixed when this package can be upgraded to PHP 7.3+.

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description
This PR fixes #16.

A few psalm issues were fixed, but i do also plan address #17 which will make it easier to solve issues with typehints instead of annotations.

Template comments require targeting the master branch? Only 2.3.x is showing up as available.

### CODE REVIEW

**Comment by datasage** [comment]
It looks like I will need to fix the PHP 7.3 support issue as well. Psalm dependencies require it or better.

**Comment by datasage** [comment]
Completing this PR is currently dependent on https://github.com/phpro/zf-doctrine-hydration-module/pull/47

**Comment by TomHAnderson** [comment]
> Completing this PR is currently dependent on [phpro/zf-doctrine-hydration-module#47](https://github.com/phpro/zf-doctrine-hydration-module/pull/47)

I notified the Laminas team about this in April:  https://github.com/laminas-api-tools/api-tools-doctrine/issues/15

**Comment by datasage** [comment]
My PR to that project does update everything as is without changing any functionality unless it was made incompatible with package changes.

At least as a short term route, we could hard fork and inherit from that going forward.

As a long term route I think the entire package should be deprecated. It seems to made up of two sets of functionality.

- MongoODM overrides for https://github.com/doctrine/doctrine-laminas-hydrator If appropriate those could be merged into that project
-  Abstract factory to handle the hydrator mapping. This could be moved into this project.

I personally don't use this for the mongo parts so its a bit difficult to make any assessment on that. If this makes sense to get this project upgraded, I can push forward with that.

**Comment by zluiten** [comment]
I'm all for forking so that https://github.com/phpro/zf-doctrine-hydration-module/pull/47 can be merged. For the long term what @datasage suggests seems to me the best way forward.

**Comment by datasage** [comment]
@netiul Its the least risky yes, in case other people are inadvertently relying on the parts not used by this library.

**Comment by weierophinney** [comment]
Closing in favor of #26. We've done incremental steps to migrate to GHA for CI, update laminas-coding-standards, update the minimum supported PHP version, and add PHP 8.0 as a supported version - which makes the Psalm additions easier.

**Pull request closed without merging**
